markdown: kramdown
permalink: /:categories/:title
url: https://bitbear.org
plugins:
  - jekyll-sitemap
  - jekyll-feed

compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

defaults:
  - values:
      layout: default
      description: |
        Bitbear.org is the website of electronic music producer Asbj√∏rn Ulsberg
  - scope:
      path: music/legacy
    values:
      layout: post

sass:
  sass_dir: assets/scss
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - readme.md
  - .gitignore
  - spec
  - Rakefile
  - coverage
